### ISSUE TITLE
Add support for radio-browser database?

### ISSUE THREAD

**Issue by Neverest** [assen-totin/mate-applet-softupd#6]
Would be nice if the applet had access to the [radio-browser](http://www.radio-browser.info/gui/#/) database since it has so many stations from different countries and languages. Maybe have a sort or tag option by country/language/genre so one can quickly find what they are looking for.

**Comment by assen-totin** [comment]
Hi,

Thanks for the suggestion!

1. You probably mean this for the Radio applet, not the Software Updates
applet.

2. With IceCast, the applet pre-fetches the list of stations, tags, URLs
etc, and saves them locally. This makes the search faster. It will be
easier if Radio Browser has a similar interface. Otherwise well need to
forward searches to their web page and process back results, which is not
very optimal.

I'll look into this in a few days.

WWell,

Assen

**Comment by Neverest** [comment]
Oh, sorry I had a lot of tabs opened when I submitted this. No wonder I couldn't find the issue on the mate-applet-streamer. 😆 I can paste the request there and you can close this one here if you like.

Thank you.

**Comment by assen-totin** [comment]
Radio Browser support added to version 0.4.0 of the applet, just released. You can get it from here, get the release tarball from www.zavedil.com/wp-content/uploads/2017/06/mate-applet-streamer-0.4.0.tar.gz or wait for your OS vendor to update.
